"""add_point_events_and_streaks

Revision ID: 1a6e9cacd115
Revises: d157f937a584
Create Date: 2026-04-11 12:31:31.941737

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6e9cacd115'
down_revision: str | None = 'd157f937a584'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_events',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action_type', sa.Enum('CHECKIN', 'WORKOUT_COMPLETE', 'STREAK_BONUS_7', 'STREAK_BONUS_30', 'TIER_PROMOTION', 'REFERRAL', 'CHALLENGE', 'REDEMPTION', 'ADMIN_ADJUSTMENT', name='pointactiontype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_events_created_at'), 'point_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_point_events_user_id'), 'point_events', ['user_id'], unique=False)
    op.create_table('user_streaks',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('freeze_available', sa.Boolean(), nullable=False),
    sa.Column('freeze_used_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_streaks_user_id'), 'user_streaks', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_streaks_user_id'), table_name='user_streaks')
    op.drop_table('user_streaks')
    op.drop_index(op.f('ix_point_events_user_id'), table_name='point_events')
    op.drop_index(op.f('ix_point_events_created_at'), table_name='point_events')
    op.drop_table('point_events')
    # ### end Alembic commands ###
